apache:
    build: .
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysqldb:mysqldb
    volumes:
      - ./www:/var/www/html
      - ./logs:/var/log/apache2
  
mysqldb:
      image: mysql:5.7.25
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: rootpass